# Generated by Django 5.0.2 on 2024-02-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "image_classification",
            "0003_image_category_image_feedback_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="feedback_created_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="image",
            name="is_correct",
            field=models.BooleanField(default=None),
        ),
    ]
